"""Deleted device_location field in Asset Class

Revision ID: 20b172bbba9a
Revises: b14d55c59d7a
Create Date: 2023-08-07 07:00:24.580384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20b172bbba9a'
down_revision = 'b14d55c59d7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'device_location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('device_location', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
