"""Changed User field

Revision ID: d7455952f778
Revises: d7bda3b6e23f
Create Date: 2023-07-30 15:17:16.212486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7455952f778'
down_revision = 'd7bda3b6e23f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
