"""Create DB

Revision ID: d7bda3b6e23f
Revises: 
Create Date: 2023-07-30 14:40:12.789161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7bda3b6e23f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lockers',
    sa.Column('locker_id', sa.Integer(), nullable=False),
    sa.Column('locker_name', sa.String(), nullable=True),
    sa.Column('locker_serial_number', sa.Integer(), nullable=True),
    sa.Column('asset_count', sa.Integer(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('locker_id')
    )
    op.create_table('users',
    sa.Column('ee_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('user_group', sa.String(), nullable=True),
    sa.Column('badge_number', sa.Integer(), nullable=True),
    sa.Column('checked_out_asset', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ee_id')
    )
    op.create_table('assets',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=True),
    sa.Column('serial_number', sa.Integer(), nullable=True),
    sa.Column('device_location', sa.Integer(), nullable=True),
    sa.Column('slot_location', sa.Integer(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('status_changed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('locker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['locker_id'], ['lockers.locker_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.ee_id'], ),
    sa.PrimaryKeyConstraint('asset_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assets')
    op.drop_table('users')
    op.drop_table('lockers')
    # ### end Alembic commands ###
